# Data Cleaning Project

## Objective
Clean and prepare dataset(s) for analysis/reporting.

## Scope
- Handle missing values
- Remove duplicates
- Fix data types
- Normalize text
- Validate data quality

## Output
- Clean dataset (CSV)

In [172]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)

In [173]:
df=pd.read_csv("data.csv")
df.head()

        order_id   order_date shipment_date    customer_name             customer_email product_category          product_name  quantity unit_price order_status    payment_method delivery_city
0  ORD-2025-0001   2025-11-03    2025-11-04         Amr Adel         amr.adel@gmail.com       Home Decor       Decorative Vase         1      40.26    Delivered       Credit Card     Beni Suef
1  ORD-2025-0002   2025-11-22    28/11/2025        Omar Taha        omar.taha@yahoo.com           Office   Ergonomic Mouse Pad         1       9.01      Shipped  Cash on Delivery      Mansoura
2  ORD-2025-0003   02/02/2025   03-Feb-2025       Salma Adel                        NaN         Kitchen   Meal Prep Containers         5      40.92    Delivered  Cash on Delivery       Zagazig
3  ORD-2025-0004  06-Nov-2025   15-Nov-2025  Youssef Ibrahim  youssef.ibrahim@proton.me       Home Decor       Decorative Vase         1      45.61     Returned       Credit Card          Giza
4  ORD-2025-0005   07/11/2025    2025-11-08      Nour Shawky      nour.shawky@gmail.com       Home Decor        LED Table Lamp         3      51.55    Delivered       Credit Card      Mansoura

In [176]:
# قبل
rows_before = df.shape[0]
duplicates = df.duplicated().sum()

invalid_dates = (df['shipment_date'] < df['order_date']).sum()

missing_shipment = df['shipment_date'].isna().sum()
missing_email = df['customer_email'].isna().sum()
missing_city = df['delivery_city'].isna().sum()

print(rows_before, duplicates, invalid_dates, missing_shipment, missing_email, missing_city)

320

In [154]:
df.info()

df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          320 non-null    object
 1   order_date        320 non-null    object
 2   shipment_date     240 non-null    object
 3   customer_name     320 non-null    object
 4   customer_email    298 non-null    object
 5   product_category  320 non-null    object
 6   product_name      320 non-null    object
 7   quantity          320 non-null    int64
 8   unit_price        320 non-null    object
 9   order_status      320 non-null    object
 10  payment_method    320 non-null    object
 11  delivery_city     307 non-null    object
dtypes: int64(1), object(11)
memory usage: 30.1+ KB

             order_id  order_date shipment_date customer_name         customer_email product_category         product_name    quantity unit_price order_status payment_method delivery_city
count             320         320           240           320                    298              320                  320  320.000000        320          320            320           307
unique            316         275           227           244                    269               19                   20         NaN        310           18             20            28
top     ORD-2025-0013  10/01/2025  Oct 11, 2025   Nour Shawky  nour.shawky@gmail.com          Storage  Plastic Storage Box         NaN       8.84    Delivered    Credit Card        Assiut
freq                2           4             2             5                      4               59                   25         NaN          2          149             89            30
mean              NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    3.612500        NaN          NaN            NaN           NaN
std               NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    1.741932        NaN          NaN            NaN           NaN
min               NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    1.000000        NaN          NaN            NaN           NaN
25%               NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    2.000000        NaN          NaN            NaN           NaN
50%               NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    4.000000        NaN          NaN            NaN           NaN
75%               NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    5.000000        NaN          NaN            NaN           NaN
max               NaN         NaN           NaN           NaN                    NaN              NaN                  NaN    6.000000        NaN          NaN            NaN           NaN

In [155]:
df.isna().sum()[lambda x: x != 0].sort_values(ascending=False)

shipment_date     80
customer_email    22
delivery_city     13
dtype: int64

In [156]:
df.duplicated().sum()

np.int64(4)

In [157]:
for col in df.select_dtypes(include="object"):
    print(f"{col}")
    print(df[col].unique()[:10],"\n")

order_id
['ORD-2025-0001' 'ORD-2025-0002' 'ORD-2025-0003' 'ORD-2025-0004'
 'ORD-2025-0005' 'ORD-2025-0006' 'ORD-2025-0007' 'ORD-2025-0008'
 'ORD-2025-0009' 'ORD-2025-0010']

order_date
['2025-11-03' '2025-11-22' '02/02/2025' '06-Nov-2025' '07/11/2025'
 '07/03/2025' '2025-12-15' '06/01/2025' '23/10/2025' '17-Aug-2025']

shipment_date
['2025-11-04' '28/11/2025' '03-Feb-2025' '15-Nov-2025' '2025-11-08' nan
 '2025-12-17' 'Jan 11, 2025' '2025-11-02' 'Nov 30, 2025']

customer_name
['Amr Adel' 'Omar Taha' 'Salma Adel' 'Youssef Ibrahim' 'Nour Shawky'
 'Heba Said' 'Lina Fathy' 'Nada Aziz' 'Nadia Mahmoud' 'Youssef Yassin']

customer_email
['amr.adel@gmail.com' 'omar.taha@yahoo.com' nan
 'youssef.ibrahim@proton.me' 'nour.shawky@gmail.com' 'heba.said@proton.me'
 'lina.fathy@gmail.com' 'nadia.mahmoud@gmail.com'
 'youssef.yassin@outlook.com' 'nour.gamal@outlook.com']

product_category
['Home Decor' 'Office' ' Kitchen ' 'Kitchen' 'storage' 'home decor'
 'Cleaning' 'Storage' ' Office ' 'office']

product_name
['Decorative Vase' 'Ergonomic Mouse Pad' 'Meal Prep Containers'
 'LED Table Lamp' 'Nonstick Pan' 'Drawer Divider Kit' 'Cutlery Set'
 'Trash Bin Liner Roll' 'Glass Storage Jar' 'Plastic Storage Box']

unit_price
['40.26' '9.01' '40.92' '45.61' '51.55' '52.53' '21.61' '43.59' '40.44'
 '54.38']

order_status
['Delivered' 'Shipped' 'Returned' 'DELIVERED' 'Processing' ' Delivered '
 'Cancelled' 'delivered' 'PROCESSING' ' Shipped ']

payment_method
['Credit Card' 'Cash on Delivery' ' card ' 'CREDIT CARD' 'PayPal'
 'Bank Transfer' 'cash on delivery' ' cod ' 'CC' 'bank transfer']

delivery_city
['Beni Suef' 'Mansoura' 'Zagazig' 'Giza' 'Port Said' ' Zagazig ' 'Minya'
 'Assiut' ' Beni Suef ' 'Ismailia']

In [158]:
df.describe()

         quantity
count  320.000000
mean     3.612500
std      1.741932
min      1.000000
25%      2.000000
50%      4.000000
75%      5.000000
max      6.000000

## Detected Issues

- Missing values in: shipment_date,customer_email,delivery_city
- Duplicates: 4 rows duplicates
- Data type issues: order_date,shipment_date-> date , unit_price->num
- Columns contain inconsistent categorical values due to case variation (e.g., "Delivered", "DELIVERED", "delivered").
- Columns contain inconsistent date formats (e.g., "2025-11-02", "15-Nov-2025", "02/02/2025").

## Cleaning Decisions

- Drop duplicates
- Handle missing values
- Normalize text (strip + lower + title)
- Convert data types

In [159]:
df=df.drop_duplicates()

In [160]:
for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip().str.lower().str.title()

df.head()

        order_id   order_date shipment_date    customer_name             customer_email product_category          product_name  quantity unit_price order_status    payment_method delivery_city
0  Ord-2025-0001   2025-11-03    2025-11-04         Amr Adel         Amr.Adel@Gmail.Com       Home Decor       Decorative Vase         1      40.26    Delivered       Credit Card     Beni Suef
1  Ord-2025-0002   2025-11-22    28/11/2025        Omar Taha        Omar.Taha@Yahoo.Com           Office   Ergonomic Mouse Pad         1       9.01      Shipped  Cash On Delivery      Mansoura
2  Ord-2025-0003   02/02/2025   03-Feb-2025       Salma Adel                        NaN          Kitchen  Meal Prep Containers         5      40.92    Delivered  Cash On Delivery       Zagazig
3  Ord-2025-0004  06-Nov-2025   15-Nov-2025  Youssef Ibrahim  Youssef.Ibrahim@Proton.Me       Home Decor       Decorative Vase         1      45.61     Returned       Credit Card          Giza
4  Ord-2025-0005   07/11/2025    2025-11-08      Nour Shawky      Nour.Shawky@Gmail.Com       Home Decor        Led Table Lamp         3      51.55    Delivered       Credit Card      Mansoura

In [161]:
df.columns = df.columns.str.strip().str.lower()
df.head()

        order_id   order_date shipment_date    customer_name             customer_email product_category          product_name  quantity unit_price order_status    payment_method delivery_city
0  Ord-2025-0001   2025-11-03    2025-11-04         Amr Adel         Amr.Adel@Gmail.Com       Home Decor       Decorative Vase         1      40.26    Delivered       Credit Card     Beni Suef
1  Ord-2025-0002   2025-11-22    28/11/2025        Omar Taha        Omar.Taha@Yahoo.Com           Office   Ergonomic Mouse Pad         1       9.01      Shipped  Cash On Delivery      Mansoura
2  Ord-2025-0003   02/02/2025   03-Feb-2025       Salma Adel                        NaN          Kitchen  Meal Prep Containers         5      40.92    Delivered  Cash On Delivery       Zagazig
3  Ord-2025-0004  06-Nov-2025   15-Nov-2025  Youssef Ibrahim  Youssef.Ibrahim@Proton.Me       Home Decor       Decorative Vase         1      45.61     Returned       Credit Card          Giza
4  Ord-2025-0005   07/11/2025    2025-11-08      Nour Shawky      Nour.Shawky@Gmail.Com       Home Decor        Led Table Lamp         3      51.55    Delivered       Credit Card      Mansoura

In [162]:
#Convert dates, nums
df["order_date"] = pd.to_datetime(df["order_date"],format="mixed",dayfirst=True, errors="coerce")
df["shipment_date"] = pd.to_datetime(df["shipment_date"],format="mixed",dayfirst=True, errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 316 entries, 0 to 315
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          316 non-null    object
 1   order_date        316 non-null    datetime64[ns]
 2   shipment_date     239 non-null    datetime64[ns]
 3   customer_name     316 non-null    object
 4   customer_email    294 non-null    object
 5   product_category  316 non-null    object
 6   product_name      316 non-null    object
 7   quantity          316 non-null    int64
 8   unit_price        316 non-null    object
 9   order_status      316 non-null    object
 10  payment_method    316 non-null    object
 11  delivery_city     303 non-null    object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 32.1+ KB

In [163]:
df["unit_price"]=df["unit_price"].replace(r"[^\d.]","",regex=True).pipe(pd.to_numeric)
df["unit_price"].isna().sum()

np.int64(0)

In [164]:
#handle with Outliers
df=df[ df["shipment_date"]>=df["order_date"]]
df=df[ df["quantity"] > 0 ]
df=df[ df["unit_price"] > 0 ]
df = df[(df['order_status'] != "Delivered") | (df['shipment_date'].notna())]
df = df[(df['order_status'] != "Shipped") | (df['shipment_date'].notna())]

In [165]:
df["customer_email"]=df["customer_email"].fillna("UNKOWN_EMAIL")
df["delivery_city"]=df["delivery_city"].fillna("UNKOWN_city")

In [166]:
df.isna().sum().sum()

np.int64(0)

In [167]:
df.duplicated().sum()

np.int64(0)

In [168]:
df.shape

(222, 12)

In [170]:
df.to_csv("clean_data.csv", index=False)

In [171]:
check = pd.read_csv("clean_data.csv")
check.head()

        order_id  order_date shipment_date    customer_name             customer_email product_category          product_name  quantity  unit_price order_status    payment_method delivery_city
0  Ord-2025-0001  2025-11-03    2025-11-04         Amr Adel         Amr.Adel@Gmail.Com       Home Decor       Decorative Vase         1       40.26    Delivered       Credit Card     Beni Suef
1  Ord-2025-0002  2025-11-22    2025-11-28        Omar Taha        Omar.Taha@Yahoo.Com           Office   Ergonomic Mouse Pad         1        9.01      Shipped  Cash On Delivery      Mansoura
2  Ord-2025-0003  2025-02-02    2025-02-03       Salma Adel               UNKOWN_EMAIL          Kitchen  Meal Prep Containers         5       40.92    Delivered  Cash On Delivery       Zagazig
3  Ord-2025-0004  2025-11-06    2025-11-15  Youssef Ibrahim  Youssef.Ibrahim@Proton.Me       Home Decor       Decorative Vase         1       45.61     Returned       Credit Card          Giza
4  Ord-2025-0005  2025-11-07    2025-11-08      Nour Shawky      Nour.Shawky@Gmail.Com       Home Decor        Led Table Lamp         3       51.55    Delivered       Credit Card      Mansoura

## Summary

- Removed duplicates
- Handled missing values
- Normalized text columns
- Fixed data types
- Dataset is ready for analysis